# Generated once from the original Trainings example data.
TRAININGS = {'initiatives': [{'name': 'Newsroom Digital Skills Training',
                  'description': 'Training cohorts, a shared digital toolkit and small grants that help independent local newsrooms build digital audiences '
                                 'and sustainable revenue.',
                  'owner': 'Nadia Hassan',
                  'start': '2026-03-01',
                  'end': '2027-02-28',
                  'budget': 420000,
                  'region': 'UK & Ireland',
                  'status': 'active',
                  'toc': {'inputs': '$420k budget including a grant fund; 3 programme staff; trainer network of 12 working journalists; shared analytics and '
                                    'CMS toolkit.',
                          'activities': 'Monthly training cohorts on audience development and revenue; toolkit onboarding and support; small grants for '
                                        'pilots; peer-learning roadshow.',
                          'outputs': '300 journalists trained; 40 newsrooms onboarded to the toolkit; 30 newsrooms using audience analytics every week.',
                          'outcomes': 'Newsrooms grow digital audiences, add new revenue streams, and staff apply new skills; local readers trust their local '
                                      'news more.',
                          'impact': 'More local news organisations are financially sustainable, so communities keep access to reliable local reporting.'},
                  'focusArea': 'Trainings'},
                 {'name': 'Newsroom Champions (internal)',
                  'description': 'News-literacy sessions for colleagues, and a champions network who explain the programme and use its stories in their own '
                                 'teams.',
                  'owner': 'Tom Reeves',
                  'start': '2026-03-01',
                  'end': '2027-02-28',
                  'budget': 60000,
                  'region': 'Global',
                  'status': 'active',
                  'toc': {'inputs': '$60k; 1 programme lead; content from the external training; support from Comms and Marketing.',
                          'activities': 'Monthly news-literacy sessions; a champions certification; an internal case-study pack.',
                          'outputs': '400 colleagues trained; 40 certified champions.',
                          'outcomes': 'Colleagues can explain the programme confidently and use its stories with partners and policymakers.',
                          'impact': 'The organisation speaks about news and journalism with one informed voice.'},
                  'focusArea': 'Trainings'}],
 'metrics': [{'initiative': 'Newsroom Digital Skills Training',
              'name': 'Training grants disbursed',
              'definition': 'Grant payments released to participating newsrooms to cover training time and pilots.',
              'level': 'input',
              'unit': '$',
              'direction': 'increase',
              'measureType': 'cumulative',
              'baseline': 0,
              'target': 300000,
              'targetDate': '',
              'frequency': 'monthly',
              'dataSource': 'Finance system',
              'isKey': False,
              'audience': 'external',
              'leadingIndicatorFor': '',
              'library': ''},
             {'initiative': 'Newsroom Digital Skills Training',
              'name': 'Training sessions delivered',
              'definition': 'Live training sessions (online or in person) of at least 90 minutes.',
              'level': 'activity',
              'unit': 'sessions',
              'direction': 'increase',
              'measureType': 'cumulative',
              'baseline': 0,
              'target': 48,
              'targetDate': '',
              'frequency': 'monthly',
              'dataSource': 'Training calendar',
              'isKey': False,
              'audience': 'external',
              'leadingIndicatorFor': '',
              'library': ''},
             {'initiative': 'Newsroom Digital Skills Training',
              'name': 'Newsrooms onboarded to digital toolkit',
              'definition': 'Newsrooms with an active toolkit account and a completed onboarding call.',
              'level': 'activity',
              'unit': 'newsrooms',
              'direction': 'increase',
              'measureType': 'cumulative',
              'baseline': 0,
              'target': 40,
              'targetDate': '',
              'frequency': 'monthly',
              'dataSource': 'Toolkit CRM',
              'isKey': False,
              'audience': 'external',
              'leadingIndicatorFor': '',
              'library': 'Organisations onboarded'},
             {'initiative': 'Newsroom Digital Skills Training',
              'name': 'Journalists trained',
              'definition': 'Unique journalists completing at least one full training session.',
              'level': 'output',
              'unit': 'people',
              'direction': 'increase',
              'measureType': 'cumulative',
              'baseline': 0,
              'target': 300,
              'targetDate': '',
              'frequency': 'monthly',
              'dataSource': 'Attendance registers',
              'isKey': True,
              'audience': 'external',
              'leadingIndicatorFor': 'Trainees applying new skills',
              'library': 'People trained'},
             {'initiative': 'Newsroom Digital Skills Training',
              'name': 'Newsrooms using analytics weekly',
              'definition': 'Newsrooms that logged into the analytics dashboard in at least 3 of the last 4 weeks.',
              'level': 'output',
              'unit': 'newsrooms',
              'direction': 'increase',
              'measureType': 'point',
              'baseline': 0,
              'target': 30,
              'targetDate': '',
              'frequency': 'monthly',
              'dataSource': 'Toolkit usage logs',
              'isKey': False,
              'audience': 'external',
              'leadingIndicatorFor': 'Average monthly digital audience per newsroom',
              'library': ''},
             {'initiative': 'Newsroom Digital Skills Training',
              'name': 'Average monthly digital audience per newsroom',
              'definition': "Median monthly unique visitors across participating newsrooms' websites.",
              'level': 'outcome',
              'unit': 'unique visitors',
              'direction': 'increase',
              'measureType': 'point',
              'baseline': 12000,
              'target': 18000,
              'targetDate': '',
              'frequency': 'monthly',
              'dataSource': 'Web analytics (shared toolkit)',
              'isKey': True,
              'audience': 'external',
              'leadingIndicatorFor': '',
              'library': ''},
             {'initiative': 'Newsroom Digital Skills Training',
              'name': 'Newsrooms with a new revenue stream',
              'definition': 'Share of participating newsrooms that launched a revenue stream (memberships, events, sponsorship) since joining.',
              'level': 'outcome',
              'unit': '%',
              'direction': 'increase',
              'measureType': 'point',
              'baseline': 15,
              'target': 50,
              'targetDate': '',
              'frequency': 'monthly',
              'dataSource': 'Monthly check-in form',
              'isKey': False,
              'audience': 'external',
              'leadingIndicatorFor': 'Financially sustainable newsrooms',
              'library': ''},
             {'initiative': 'Newsroom Digital Skills Training',
              'name': 'Trainees applying new skills',
              'definition': 'Share of trainees who report using a technique from training in the last month, surveyed 8+ weeks after training.',
              'level': 'outcome',
              'unit': '%',
              'direction': 'increase',
              'measureType': 'point',
              'baseline': 0,
              'target': 70,
              'targetDate': '',
              'frequency': 'quarterly',
              'dataSource': 'Follow-up survey',
              'isKey': False,
              'audience': 'external',
              'leadingIndicatorFor': '',
              'library': 'Trainees applying new skills'},
             {'initiative': 'Newsroom Digital Skills Training',
              'name': 'Reader trust score',
              'definition': "Mean answer to 'How much do you trust this outlet?' on a 1-10 scale, across participating newsrooms' reader surveys.",
              'level': 'outcome',
              'unit': 'score (1-10)',
              'direction': 'increase',
              'measureType': 'point',
              'baseline': 6.2,
              'target': 7,
              'targetDate': '',
              'frequency': 'quarterly',
              'dataSource': 'Reader survey',
              'isKey': False,
              'audience': 'external',
              'leadingIndicatorFor': '',
              'library': 'Audience trust score'},
             {'initiative': 'Newsroom Digital Skills Training',
              'name': 'Financially sustainable newsrooms',
              'definition': 'Participating newsrooms whose revenue covers operating costs for 3 consecutive months.',
              'level': 'impact',
              'unit': 'newsrooms',
              'direction': 'increase',
              'measureType': 'point',
              'baseline': 8,
              'target': 20,
              'targetDate': '',
              'frequency': 'quarterly',
              'dataSource': 'Financial returns (modelled from partial data)',
              'isKey': True,
              'audience': 'external',
              'leadingIndicatorFor': '',
              'library': ''},
             {'initiative': 'Newsroom Champions (internal)',
              'name': 'Colleagues completing news-literacy training',
              'definition': '',
              'level': 'output',
              'unit': 'people',
              'direction': 'increase',
              'measureType': 'cumulative',
              'baseline': 0,
              'target': 400,
              'targetDate': '',
              'frequency': 'monthly',
              'dataSource': 'Learning platform',
              'isKey': True,
              'audience': 'internal',
              'leadingIndicatorFor': '',
              'library': ''},
             {'initiative': 'Newsroom Champions (internal)',
              'name': 'Certified internal champions',
              'definition': '',
              'level': 'output',
              'unit': 'champions',
              'direction': 'increase',
              'measureType': 'cumulative',
              'baseline': 0,
              'target': 40,
              'targetDate': '',
              'frequency': 'monthly',
              'dataSource': 'Champions register',
              'isKey': False,
              'audience': 'internal',
              'leadingIndicatorFor': 'Colleagues confident explaining the programme',
              'library': ''},
             {'initiative': 'Newsroom Champions (internal)',
              'name': 'Colleagues confident explaining the programme',
              'definition': '',
              'level': 'outcome',
              'unit': '%',
              'direction': 'increase',
              'measureType': 'point',
              'baseline': 35,
              'target': 70,
              'targetDate': '',
              'frequency': 'quarterly',
              'dataSource': 'Quarterly pulse survey',
              'isKey': True,
              'audience': 'internal',
              'leadingIndicatorFor': '',
              'library': ''},
             {'initiative': 'Newsroom Champions (internal)',
              'name': 'Teams using programme case studies',
              'definition': '',
              'level': 'outcome',
              'unit': 'teams',
              'direction': 'increase',
              'measureType': 'point',
              'baseline': 0,
              'target': 15,
              'targetDate': '',
              'frequency': 'monthly',
              'dataSource': 'Comms request log',
              'isKey': False,
              'audience': 'internal',
              'leadingIndicatorFor': '',
              'library': ''}],
 'entries': [{'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training grants disbursed',
              'date': '2026-04-01',
              'value': 20000,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training grants disbursed',
              'date': '2026-05-01',
              'value': 17000,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training grants disbursed',
              'date': '2026-06-01',
              'value': 23000,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training grants disbursed',
              'date': '2026-07-01',
              'value': 20000,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training grants disbursed',
              'date': '2026-08-01',
              'value': 17000,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training grants disbursed',
              'date': '2026-09-01',
              'value': 23000,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training sessions delivered',
              'date': '2026-04-01',
              'value': 4,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training sessions delivered',
              'date': '2026-05-01',
              'value': 4,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training sessions delivered',
              'date': '2026-06-01',
              'value': 5,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training sessions delivered',
              'date': '2026-07-01',
              'value': 5,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training sessions delivered',
              'date': '2026-08-01',
              'value': 4,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Training sessions delivered',
              'date': '2026-09-01',
              'value': 5,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms onboarded to digital toolkit',
              'date': '2026-04-01',
              'value': 3,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms onboarded to digital toolkit',
              'date': '2026-05-01',
              'value': 5,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms onboarded to digital toolkit',
              'date': '2026-06-01',
              'value': 6,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms onboarded to digital toolkit',
              'date': '2026-07-01',
              'value': 4,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms onboarded to digital toolkit',
              'date': '2026-08-01',
              'value': 5,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms onboarded to digital toolkit',
              'date': '2026-09-01',
              'value': 4,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Journalists trained',
              'date': '2026-04-01',
              'value': 18,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Journalists trained',
              'date': '2026-05-01',
              'value': 22,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Journalists trained',
              'date': '2026-06-01',
              'value': 30,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Journalists trained',
              'date': '2026-07-01',
              'value': 28,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Journalists trained',
              'date': '2026-08-01',
              'value': 24,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Journalists trained',
              'date': '2026-09-01',
              'value': 26,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms using analytics weekly',
              'date': '2026-04-01',
              'value': 2,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms using analytics weekly',
              'date': '2026-05-01',
              'value': 5,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms using analytics weekly',
              'date': '2026-06-01',
              'value': 8,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms using analytics weekly',
              'date': '2026-07-01',
              'value': 10,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms using analytics weekly',
              'date': '2026-08-01',
              'value': 11,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms using analytics weekly',
              'date': '2026-09-01',
              'value': 12,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Average monthly digital audience per newsroom',
              'date': '2026-04-01',
              'value': 12100,
              'confidence': 'estimated',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Average monthly digital audience per newsroom',
              'date': '2026-05-01',
              'value': 12400,
              'confidence': 'estimated',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Average monthly digital audience per newsroom',
              'date': '2026-06-01',
              'value': 12900,
              'confidence': 'estimated',
              'note': 'Jump partly from the YouTube series driving traffic to partner sites.',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Average monthly digital audience per newsroom',
              'date': '2026-07-01',
              'value': 13100,
              'confidence': 'estimated',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Average monthly digital audience per newsroom',
              'date': '2026-08-01',
              'value': 13300,
              'confidence': 'estimated',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Average monthly digital audience per newsroom',
              'date': '2026-09-01',
              'value': 13500,
              'confidence': 'estimated',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms with a new revenue stream',
              'date': '2026-04-01',
              'value': 15,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms with a new revenue stream',
              'date': '2026-05-01',
              'value': 18,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms with a new revenue stream',
              'date': '2026-06-01',
              'value': 22,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms with a new revenue stream',
              'date': '2026-07-01',
              'value': 26,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms with a new revenue stream',
              'date': '2026-08-01',
              'value': 30,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Newsrooms with a new revenue stream',
              'date': '2026-09-01',
              'value': 33,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Trainees applying new skills',
              'date': '2026-06-01',
              'value': 58,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Trainees applying new skills',
              'date': '2026-09-01',
              'value': 64,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Reader trust score',
              'date': '2026-06-01',
              'value': 6.4,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Reader trust score',
              'date': '2026-09-01',
              'value': 6.5,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Financially sustainable newsrooms',
              'date': '2026-04-01',
              'value': 8,
              'confidence': 'modelled',
              'note': '',
              'loggedBy': 'Nadia Hassan'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Financially sustainable newsrooms',
              'date': '2026-07-01',
              'value': 10,
              'confidence': 'modelled',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Digital Skills Training',
              'metric': 'Financially sustainable newsrooms',
              'date': '2026-09-01',
              'value': 11,
              'confidence': 'modelled',
              'note': "Modelled from 14 of 22 newsrooms' returns; remainder due in October.",
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Colleagues completing news-literacy training',
              'date': '2026-04-01',
              'value': 30,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Colleagues completing news-literacy training',
              'date': '2026-05-01',
              'value': 45,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Colleagues completing news-literacy training',
              'date': '2026-06-01',
              'value': 40,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Colleagues completing news-literacy training',
              'date': '2026-07-01',
              'value': 25,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Colleagues completing news-literacy training',
              'date': '2026-08-01',
              'value': 20,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Colleagues completing news-literacy training',
              'date': '2026-09-01',
              'value': 35,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Certified internal champions',
              'date': '2026-04-01',
              'value': 0,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Certified internal champions',
              'date': '2026-05-01',
              'value': 4,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Certified internal champions',
              'date': '2026-06-01',
              'value': 3,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Certified internal champions',
              'date': '2026-07-01',
              'value': 2,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Certified internal champions',
              'date': '2026-08-01',
              'value': 1,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Certified internal champions',
              'date': '2026-09-01',
              'value': 3,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Colleagues confident explaining the programme',
              'date': '2026-06-01',
              'value': 41,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Colleagues confident explaining the programme',
              'date': '2026-09-01',
              'value': 44,
              'confidence': 'self-reported',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Teams using programme case studies',
              'date': '2026-04-01',
              'value': 1,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Teams using programme case studies',
              'date': '2026-05-01',
              'value': 2,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Teams using programme case studies',
              'date': '2026-06-01',
              'value': 4,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Teams using programme case studies',
              'date': '2026-07-01',
              'value': 5,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Teams using programme case studies',
              'date': '2026-08-01',
              'value': 7,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'},
             {'initiative': 'Newsroom Champions (internal)',
              'metric': 'Teams using programme case studies',
              'date': '2026-09-01',
              'value': 9,
              'confidence': 'measured',
              'note': '',
              'loggedBy': 'Tom Reeves'}],
 'campaigns': [{'initiative': 'Newsroom Digital Skills Training',
                'name': 'Local News Matters (YouTube series)',
                'channel': 'youtube',
                'audience': 'external',
                'start': '2026-04-15',
                'end': '2026-06-30',
                'spend': 12000,
                'tag': 'utm_campaign=lnm_youtube_2026',
                'notes': 'Six short documentaries on local newsrooms, each linking to the featured outlet.'},
               {'initiative': 'Newsroom Digital Skills Training',
                'name': 'Toolkit launch email series',
                'channel': 'email',
                'audience': 'external',
                'start': '2026-05-01',
                'end': '2026-05-31',
                'spend': 1500,
                'tag': 'utm_campaign=toolkit_launch',
                'notes': 'Four-email sequence to 2,300 local editors and publishers.'},
               {'initiative': 'Newsroom Digital Skills Training',
                'name': 'Newsroom Futures roadshow',
                'channel': 'events',
                'audience': 'external',
                'start': '2026-07-01',
                'end': '2026-08-31',
                'spend': 18000,
                'tag': 'EVT-NF26',
                'notes': 'Five regional half-day events with peer case studies and toolkit demos.'},
               {'initiative': 'Newsroom Champions (internal)',
                'name': 'Internal launch: town hall and newsletter',
                'channel': 'events',
                'audience': 'internal',
                'start': '2026-04-20',
                'end': '2026-05-15',
                'spend': 3500,
                'tag': 'INT-LAUNCH-26',
                'notes': 'Global town hall with the Comms team, followed by a four-part internal newsletter.'}],
 'campaignMetrics': [{'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-04-01',
                      'metric': 'clicks',
                      'value': 1400},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-04-01',
                      'metric': 'impressions',
                      'value': 85000},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-04-01',
                      'metric': 'sign-ups',
                      'value': 90},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-04-01',
                      'metric': 'views',
                      'value': 21000},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-05-01',
                      'metric': 'clicks',
                      'value': 3100},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-05-01',
                      'metric': 'impressions',
                      'value': 160000},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-05-01',
                      'metric': 'sign-ups',
                      'value': 240},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-05-01',
                      'metric': 'views',
                      'value': 46000},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-06-01',
                      'metric': 'clicks',
                      'value': 2700},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-06-01',
                      'metric': 'impressions',
                      'value': 140000},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-06-01',
                      'metric': 'sign-ups',
                      'value': 210},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Local News Matters (YouTube series)',
                      'date': '2026-06-01',
                      'metric': 'views',
                      'value': 39000},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Toolkit launch email series',
                      'date': '2026-05-01',
                      'metric': 'clicks',
                      'value': 620},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Toolkit launch email series',
                      'date': '2026-05-01',
                      'metric': 'opens',
                      'value': 3900},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Toolkit launch email series',
                      'date': '2026-05-01',
                      'metric': 'sent',
                      'value': 9200},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Toolkit launch email series',
                      'date': '2026-05-01',
                      'metric': 'sign-ups',
                      'value': 41},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Newsroom Futures roadshow',
                      'date': '2026-07-01',
                      'metric': 'attendees',
                      'value': 140},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Newsroom Futures roadshow',
                      'date': '2026-07-01',
                      'metric': 'sign-ups',
                      'value': 18},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Newsroom Futures roadshow',
                      'date': '2026-08-01',
                      'metric': 'attendees',
                      'value': 165},
                     {'initiative': 'Newsroom Digital Skills Training',
                      'campaign': 'Newsroom Futures roadshow',
                      'date': '2026-08-01',
                      'metric': 'sign-ups',
                      'value': 23},
                     {'initiative': 'Newsroom Champions (internal)',
                      'campaign': 'Internal launch: town hall and newsletter',
                      'date': '2026-04-01',
                      'metric': 'attendees',
                      'value': 620},
                     {'initiative': 'Newsroom Champions (internal)',
                      'campaign': 'Internal launch: town hall and newsletter',
                      'date': '2026-05-01',
                      'metric': 'opens',
                      'value': 4100},
                     {'initiative': 'Newsroom Champions (internal)',
                      'campaign': 'Internal launch: town hall and newsletter',
                      'date': '2026-05-01',
                      'metric': 'sign-ups',
                      'value': 85}],
 'evidence': [{'initiative': 'Newsroom Digital Skills Training',
               'metric': 'Financially sustainable newsrooms',
               'type': 'quote',
               'title': 'Publisher on sustainability',
               'body': "We're closer, but one big advertiser leaving would still put us back in the red. The grant bought us time to diversify.",
               'source': 'Publisher, Morecambe Bay News',
               'url': '',
               'date': '2026-09-15',
               'tags': 'sustainability,risk',
               'origin': 'human'},
              {'initiative': 'Newsroom Digital Skills Training',
               'metric': 'Newsrooms with a new revenue stream',
               'type': 'survey',
               'title': 'Theme: memberships are the most common new revenue stream',
               'body': 'Across 38 check-in responses, memberships (14) and local events (9) were the most-cited new revenue streams. Sentiment is mostly '
                       'positive, with concern about sustaining member numbers after launch.',
               'source': 'AI theme coding of monthly check-in forms',
               'url': '',
               'date': '2026-09-12',
               'tags': 'revenue,theme',
               'origin': 'ai'},
              {'initiative': 'Newsroom Digital Skills Training',
               'metric': 'Trainees applying new skills',
               'type': 'survey',
               'title': 'Follow-up survey, cohort 1-3 (n=112)',
               'body': '64% say they used a technique from training in the last month. Most cited: headline testing (41%), newsletter segmentation (29%), '
                       'audience surveys (18%).',
               'source': 'Follow-up survey, September',
               'url': '',
               'date': '2026-09-10',
               'tags': 'skills,survey',
               'origin': 'human'},
              {'initiative': 'Newsroom Digital Skills Training',
               'metric': 'Reader trust score',
               'type': 'quote',
               'title': 'Reader survey comment',
               'body': "They actually come to the meetings now and explain what the decisions mean for us. That's why I read them.",
               'source': 'Reader, Hebden Bridge',
               'url': '',
               'date': '2026-09-02',
               'tags': 'trust,readers',
               'origin': 'human'},
              {'initiative': 'Newsroom Digital Skills Training',
               'metric': 'Newsrooms with a new revenue stream',
               'type': 'case-study',
               'title': 'Tyneside Tribune launches a membership scheme',
               'body': 'After the revenue cohort, the Tribune launched a $5/month membership with a members-only newsletter. 310 members joined in the first '
                       'six weeks, covering one part-time reporter.',
               'source': 'Programme case study',
               'url': '',
               'date': '2026-08-05',
               'tags': 'revenue,membership',
               'origin': 'human'},
              {'initiative': 'Newsroom Digital Skills Training',
               'metric': '',
               'type': 'link',
               'title': 'Regional press coverage of the roadshow',
               'body': "Article on the Newsroom Futures roadshow and the programme's aims.",
               'source': 'Regional business press',
               'url': 'https://example.org/press/newsroom-futures',
               'date': '2026-07-22',
               'tags': 'press',
               'origin': 'human'},
              {'initiative': 'Newsroom Digital Skills Training',
               'metric': 'Trainees applying new skills',
               'type': 'quote',
               'title': 'Trainee on newsletter skills',
               'body': 'I rebuilt our newsletter the week after the session. Open rates went from 22% to 38%.',
               'source': 'Reporter, Wharfedale Weekly',
               'url': '',
               'date': '2026-06-30',
               'tags': 'skills,newsletter',
               'origin': 'human'},
              {'initiative': 'Newsroom Digital Skills Training',
               'metric': 'Average monthly digital audience per newsroom',
               'type': 'quote',
               'title': 'Editor on the analytics dashboard',
               'body': "For the first time we can see which stories people actually finish. We've moved our council coverage to the morning slot and it's our "
                       'most-read section now.',
               'source': 'Editor, Calder Valley Voice',
               'url': '',
               'date': '2026-06-18',
               'tags': 'analytics,audience',
               'origin': 'human'},
              {'initiative': 'Newsroom Champions (internal)',
               'metric': 'Colleagues confident explaining the programme',
               'type': 'quote',
               'title': 'Policy colleague on the champions session',
               'body': 'I used the local newsroom examples in a meeting with a ministry team the following week. Having real numbers made the conversation '
                       'much easier.',
               'source': 'Champion, Government Affairs & Public Policy',
               'url': '',
               'date': '2026-09-08',
               'tags': 'gapp,champions',
               'origin': 'human'}],
 'library': [{'id': 'lib0',
              'name': 'Audience trust score',
              'definition': "Mean answer to 'How much do you trust this outlet?' on a 1-10 scale.",
              'level': 'outcome',
              'unit': 'score (1-10)',
              'direction': 'increase',
              'measureType': 'point',
              'frequency': 'quarterly',
              'dataSource': 'Reader survey'},
             {'id': 'lib1',
              'name': 'Organisations onboarded',
              'definition': 'Organisations with an active account and a completed onboarding call.',
              'level': 'activity',
              'unit': 'organisations',
              'direction': 'increase',
              'measureType': 'cumulative',
              'frequency': 'monthly',
              'dataSource': 'CRM'},
             {'id': 'lib2',
              'name': 'People trained',
              'definition': 'Unique people completing at least one full training session.',
              'level': 'output',
              'unit': 'people',
              'direction': 'increase',
              'measureType': 'cumulative',
              'frequency': 'monthly',
              'dataSource': 'Attendance registers'},
             {'id': 'lib3',
              'name': 'Trainees applying new skills',
              'definition': 'Share of trainees who report using a technique from training in the last month, surveyed 8+ weeks after training.',
              'level': 'outcome',
              'unit': '%',
              'direction': 'increase',
              'measureType': 'point',
              'frequency': 'quarterly',
              'dataSource': 'Follow-up survey'}],
 'responsibilities': [{'title': 'Q2 report to funders',
                       'description': '',
                       'type': 'report',
                       'team': 'programme',
                       'owner': 'Tom Reeves',
                       'dueDate': '2026-07-15',
                       'recurrence': 'quarterly',
                       'status': 'done',
                       'completedAt': '2026-07-14',
                       'notes': '',
                       'focusArea': 'Trainings',
                       'initiative': ''},
                      {'title': 'Impact figures for the corporate annual report',
                       'description': 'Five headline stats and two case studies, cleared for external use.',
                       'type': 'report',
                       'team': 'comms',
                       'owner': 'Priya Shah',
                       'dueDate': '2026-09-15',
                       'recurrence': 'none',
                       'status': 'open',
                       'completedAt': '',
                       'notes': '',
                       'focusArea': 'Trainings',
                       'initiative': ''},
                      {'title': 'Renew analytics toolkit vendor contract',
                       'description': 'Current licence ends in October. Vendor has proposed a 12% increase.',
                       'type': 'contract',
                       'team': 'programme',
                       'owner': 'Nadia Hassan',
                       'dueDate': '2026-09-20',
                       'recurrence': 'none',
                       'status': 'in-progress',
                       'completedAt': '',
                       'notes': '',
                       'focusArea': 'Trainings',
                       'initiative': 'Newsroom Digital Skills Training'},
                      {'title': 'Sign off champions certification',
                       'description': '',
                       'type': 'approval',
                       'team': 'programme',
                       'owner': 'Tom Reeves',
                       'dueDate': '2026-09-26',
                       'recurrence': 'none',
                       'status': 'open',
                       'completedAt': '',
                       'notes': '',
                       'focusArea': 'Trainings',
                       'initiative': 'Newsroom Champions (internal)'},
                      {'title': 'Approve monthly expenses',
                       'description': '',
                       'type': 'approval',
                       'team': 'programme',
                       'owner': 'Nadia Hassan',
                       'dueDate': '2026-09-30',
                       'recurrence': 'monthly',
                       'status': 'open',
                       'completedAt': '',
                       'notes': '',
                       'focusArea': 'Trainings',
                       'initiative': ''},
                      {'title': 'Policy briefing: local news and democracy',
                       'description': 'Briefing for the ministry roundtable, using headline figures and newsroom case studies.',
                       'type': 'report',
                       'team': 'gapp',
                       'owner': 'Daniel Mensah',
                       'dueDate': '2026-10-02',
                       'recurrence': 'none',
                       'status': 'in-progress',
                       'completedAt': '',
                       'notes': '',
                       'focusArea': 'Trainings',
                       'initiative': ''},
                      {'title': 'Q4 recruitment plan for training cohorts',
                       'description': '',
                       'type': 'admin',
                       'team': 'marketing',
                       'owner': 'Sofia Lindqvist',
                       'dueDate': '2026-10-10',
                       'recurrence': 'none',
                       'status': 'open',
                       'completedAt': '',
                       'notes': '',
                       'focusArea': 'Trainings',
                       'initiative': 'Newsroom Digital Skills Training'},
                      {'title': 'Q3 report to funders',
                       'description': 'Progress against targets, spend and case studies. Use the Q3 snapshot.',
                       'type': 'report',
                       'team': 'programme',
                       'owner': 'Tom Reeves',
                       'dueDate': '2026-10-15',
                       'recurrence': 'quarterly',
                       'status': 'open',
                       'completedAt': '',
                       'notes': '',
                       'focusArea': 'Trainings',
                       'initiative': ''},
                      {'title': 'Grant agreements for cohort 4 newsrooms',
                       'description': '',
                       'type': 'contract',
                       'team': 'programme',
                       'owner': 'Tom Reeves',
                       'dueDate': '2026-10-31',
                       'recurrence': 'none',
                       'status': 'open',
                       'completedAt': '',
                       'notes': '',
                       'focusArea': 'Trainings',
                       'initiative': 'Newsroom Digital Skills Training'},
                      {'title': 'Safeguarding and data protection review',
                       'description': '',
                       'type': 'compliance',
                       'team': 'programme',
                       'owner': 'Nadia Hassan',
                       'dueDate': '2026-11-30',
                       'recurrence': 'annually',
                       'status': 'open',
                       'completedAt': '',
                       'notes': '',
                       'focusArea': 'Trainings',
                       'initiative': ''}],
 'risks': [{'title': 'Digital audience growth misses target',
            'description': 'Audience growth is off track and its leading indicator (weekly analytics use) is behind.',
            'likelihood': 4,
            'impact': 4,
            'mitigation': 'One-to-one analytics coaching for the 18 newsrooms not yet using the dashboard weekly.',
            'status': 'open',
            'owner': 'Tom Reeves',
            'reviewDate': '2026-10-01',
            'focusArea': 'Trainings',
            'initiative': 'Newsroom Digital Skills Training'},
           {'title': 'Partner newsrooms drop out before cohort 4',
            'description': '',
            'likelihood': 3,
            'impact': 4,
            'mitigation': 'Monthly check-ins; grant tranches tied to attendance; peer mentoring pairs.',
            'status': 'open',
            'owner': 'Tom Reeves',
            'reviewDate': '2026-10-15',
            'focusArea': 'Trainings',
            'initiative': 'Newsroom Digital Skills Training'},
           {'title': 'Toolkit vendor price rise at renewal',
            'description': '',
            'likelihood': 4,
            'impact': 3,
            'mitigation': 'Negotiate a two-year rate; price an alternative supplier by end of September.',
            'status': 'open',
            'owner': 'Nadia Hassan',
            'reviewDate': '2026-09-15',
            'focusArea': 'Trainings',
            'initiative': 'Newsroom Digital Skills Training'},
           {'title': 'Data protection issue with shared newsroom analytics',
            'description': '',
            'likelihood': 2,
            'impact': 5,
            'mitigation': 'Data processing agreements signed with all newsrooms; access reviewed quarterly.',
            'status': 'mitigating',
            'owner': 'Nadia Hassan',
            'reviewDate': '2026-11-30',
            'focusArea': 'Trainings',
            'initiative': ''},
           {'title': 'Internal budget underspent and returned at year end',
            'description': '',
            'likelihood': 3,
            'impact': 2,
            'mitigation': 'Extend champions sessions to regional offices from October.',
            'status': 'open',
            'owner': 'Nadia Hassan',
            'reviewDate': '2026-10-31',
            'focusArea': 'Trainings',
            'initiative': 'Newsroom Champions (internal)'},
           {'title': 'Ministry roundtable postponed',
            'description': '',
            'likelihood': 2,
            'impact': 3,
            'mitigation': 'Prepare a written briefing that can be sent if the meeting slips.',
            'status': 'open',
            'owner': 'Daniel Mensah',
            'reviewDate': '2026-10-01',
            'focusArea': 'Trainings',
            'initiative': ''}],
 'decisions': [{'date': '2026-09-10',
                'title': 'Extend champions sessions to regional offices',
                'decision': 'Run champions sessions in four regional offices from October.',
                'rationale': 'Internal spend is well behind the timeline and demand from regional teams is high.',
                'madeBy': 'Nadia Hassan (Global lead)',
                'focusArea': 'Trainings',
                'initiative': 'Newsroom Champions (internal)'},
               {'date': '2026-07-08',
                'title': 'Report Q2 from a frozen snapshot',
                'decision': 'Board and funder reports use the Q2 snapshot, not live figures.',
                'rationale': "Figures shared with the board shouldn't change when late data arrives.",
                'madeBy': 'Programme board',
                'focusArea': 'Trainings',
                'initiative': ''},
               {'date': '2026-06-20',
                'title': 'Fund a memberships pilot',
                'decision': 'Up to $15k of grant budget goes to five newsrooms piloting memberships.',
                'rationale': 'Memberships were the most common new revenue stream; a pilot tests whether support speeds it up.',
                'madeBy': 'Nadia Hassan (Global lead)',
                'focusArea': 'Trainings',
                'initiative': 'Newsroom Digital Skills Training'},
               {'date': '2026-05-12',
                'title': 'Move revenue training earlier in each cohort',
                'decision': 'Revenue sessions move from week 6 to week 2.',
                'rationale': 'Early cohorts said they needed revenue ideas before planning audience work.',
                'madeBy': 'Programme board',
                'focusArea': 'Trainings',
                'initiative': 'Newsroom Digital Skills Training'}],
 'spend': [{'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-03-28',
            'amount': 10000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Programme staff and trainers',
            'reference': 'PAY-03'},
           {'initiative': 'Newsroom Champions (internal)',
            'date': '2026-03-28',
            'amount': 2000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Session facilitation',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-04-15',
            'amount': 24000,
            'category': 'vendors',
            'status': 'actual',
            'description': 'Analytics and CMS toolkit licence (annual)',
            'reference': 'PO-4102'},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-04-28',
            'amount': 10000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Programme staff and trainers',
            'reference': 'PAY-04'},
           {'initiative': 'Newsroom Champions (internal)',
            'date': '2026-04-28',
            'amount': 2000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Session facilitation',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-04-28',
            'amount': 20000,
            'category': 'grants',
            'status': 'actual',
            'description': 'Newsroom training grants',
            'reference': 'GR-04'},
           {'initiative': 'Newsroom Champions (internal)',
            'date': '2026-04-30',
            'amount': 3500,
            'category': 'events',
            'status': 'actual',
            'description': 'Internal launch town hall',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-05-28',
            'amount': 10000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Programme staff and trainers',
            'reference': 'PAY-05'},
           {'initiative': 'Newsroom Champions (internal)',
            'date': '2026-05-28',
            'amount': 2000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Session facilitation',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-05-28',
            'amount': 17000,
            'category': 'grants',
            'status': 'actual',
            'description': 'Newsroom training grants',
            'reference': 'GR-05'},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-05-31',
            'amount': 1500,
            'category': 'marketing',
            'status': 'actual',
            'description': 'Toolkit launch email series',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-06-15',
            'amount': 6000,
            'category': 'travel',
            'status': 'actual',
            'description': 'Trainer travel, cohorts 1-3',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-06-28',
            'amount': 10000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Programme staff and trainers',
            'reference': 'PAY-06'},
           {'initiative': 'Newsroom Champions (internal)',
            'date': '2026-06-28',
            'amount': 2000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Session facilitation',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-06-28',
            'amount': 23000,
            'category': 'grants',
            'status': 'actual',
            'description': 'Newsroom training grants',
            'reference': 'GR-06'},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-06-30',
            'amount': 12000,
            'category': 'marketing',
            'status': 'actual',
            'description': 'Local News Matters YouTube series production',
            'reference': 'PO-4410'},
           {'initiative': 'Newsroom Champions (internal)',
            'date': '2026-06-30',
            'amount': 1000,
            'category': 'other',
            'status': 'actual',
            'description': 'Champions certificates and materials',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-07-28',
            'amount': 10000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Programme staff and trainers',
            'reference': 'PAY-07'},
           {'initiative': 'Newsroom Champions (internal)',
            'date': '2026-07-28',
            'amount': 2000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Session facilitation',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-07-28',
            'amount': 20000,
            'category': 'grants',
            'status': 'actual',
            'description': 'Newsroom training grants',
            'reference': 'GR-07'},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-07-31',
            'amount': 9000,
            'category': 'events',
            'status': 'actual',
            'description': 'Newsroom Futures roadshow: venues and catering (July)',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-08-28',
            'amount': 10000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Programme staff and trainers',
            'reference': 'PAY-08'},
           {'initiative': 'Newsroom Champions (internal)',
            'date': '2026-08-28',
            'amount': 2000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Session facilitation',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-08-28',
            'amount': 17000,
            'category': 'grants',
            'status': 'actual',
            'description': 'Newsroom training grants',
            'reference': 'GR-08'},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-08-31',
            'amount': 9000,
            'category': 'events',
            'status': 'actual',
            'description': 'Newsroom Futures roadshow: venues and catering (August)',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-09-28',
            'amount': 10000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Programme staff and trainers',
            'reference': 'PAY-09'},
           {'initiative': 'Newsroom Champions (internal)',
            'date': '2026-09-28',
            'amount': 2000,
            'category': 'staff',
            'status': 'actual',
            'description': 'Session facilitation',
            'reference': ''},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-09-28',
            'amount': 23000,
            'category': 'grants',
            'status': 'actual',
            'description': 'Newsroom training grants',
            'reference': 'GR-09'},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-10-20',
            'amount': 15000,
            'category': 'events',
            'status': 'committed',
            'description': 'Cohort 7 venue booking',
            'reference': 'PO-5530'},
           {'initiative': 'Newsroom Digital Skills Training',
            'date': '2026-11-01',
            'amount': 10000,
            'category': 'vendors',
            'status': 'committed',
            'description': 'Toolkit support contract (Q4)',
            'reference': 'PO-5541'}],
 'people': [{'name': 'Nadia Hassan', 'email': 'lead@example.org', 'role': 'admin', 'team': ''},
            {'name': 'Tom Reeves', 'email': 'programme@example.org', 'role': 'programme', 'team': ''},
            {'name': 'Priya Shah', 'email': 'comms@example.org', 'role': 'partner', 'team': 'comms'},
            {'name': 'Daniel Mensah', 'email': 'gapp@example.org', 'role': 'partner', 'team': 'gapp'},
            {'name': 'Sofia Lindqvist', 'email': 'marketing@example.org', 'role': 'partner', 'team': 'marketing'}],
 'programme': {'name': 'Global News Programme',
               'mission': 'Help news organisations and the people who work with them build the skills, audiences and support that keep reliable journalism '
                          'going.',
               'description': "A global programme run with Comms, Government Affairs & Public Policy and Marketing. This year's focus is training, for "
                              'newsrooms outside the organisation and for colleagues inside it.',
               'currency': 'USD',
               'budget': 500000,
               'start': '2026-03-01',
               'end': '2027-02-28'},
 'focusAreas': [{'name': 'Trainings',
                 'description': 'Skills training for journalists and newsrooms (external), and news-literacy training that turns colleagues into programme '
                                'champions (internal).',
                 'owner': 'Nadia Hassan',
                 'budget': 500000}]}
