// Generates prisma/postgres/schema.prisma from the main (SQLite) schema by
// swapping the datasource provider. Local development keeps SQLite with no
// setup; hosted deployments use this Postgres copy. Run after editing
// prisma/schema.prisma:  npm run db:postgres-schema
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const src = readFileSync("prisma/schema.prisma", "utf8");
const out = src.replace(/provider\s*=\s*"sqlite"/, 'provider = "postgresql"');
if (out === src) throw new Error('Expected provider = "sqlite" in prisma/schema.prisma');
mkdirSync("prisma/postgres", { recursive: true });
writeFileSync(
  "prisma/postgres/schema.prisma",
  "// GENERATED by scripts/postgres-schema.mjs from prisma/schema.prisma. Do not edit by hand.\n\n" + out,
);
console.log("Wrote prisma/postgres/schema.prisma");
